#' Perform a PWM regression
#'
#' Fits a PWM (and a spatial model) that predicts \code{response} from \code{sequences}.
#' The function operates in one of three modes depending on its arguments:
#'
#' \describe{
#' \item{Single motif from a fixed seed (\code{motif} given):}{One PWM is optimized
#' starting from the supplied kmer or PSSM. Returns a single regression result.}
#' \item{Single motif from a kmer screen (\code{motif = NULL}, \code{multi_kmers = TRUE}, default):}{
#' Candidate kmer seeds are generated by \code{screen_kmers}, each is regressed on
#' a train/validation split, the best by validation score is refit on the full
#' data. Returns a single regression result. Set \code{return_all = TRUE} to get
#' \emph{all} candidate-kmer regressions instead of just the best - useful when you
#' want the top N motifs without the residual-rounds approach used by
#' \code{motif_num > 1}.}
#' \item{Multiple motifs via residual rounds (\code{motif_num > 1}):}{Delegates to
#' \code{\link{regress_multiple_motifs}}. Each successive motif is fit against the
#' residual of a linear model of the previous motifs. Returns a multi-motif result
#' (see \emph{Value}).}
#' }
#'
#' @param sequences A vector of DNA sequences ('A', 'T', 'C' or 'G'. Will go through \code{toupper}). Sequences must be long enough to cover \code{spat_num_bins} * \code{spat_bin_size} bp, and should be centered around the motif/signal.
#' @param response A matrix (or vector) of response variables. The number of rows must equal the number of sequences. A single binary vector (0/1) is required when \code{score_metric = "ks"}.
#' @param motif Initial seed for the regression. Either a kmer string ("*" denotes a wildcard) or a data frame with a pre-computed PSSM (same shape as the \code{pssm} slot of the return value). If \code{NULL} (default), a kmer screen finds a seed automatically. Ignored when \code{init_from_dataset = TRUE}.
#' @param init_from_dataset If TRUE, initialize from the best-matching PSSM in \code{motif_dataset} (chosen by \code{final_metric}; see \code{\link{screen_pwm}}). Overrides \code{motif}.
#' @param motif_length Length of the seed motif. Shorter seeds are padded with wildcards; longer seeds are \emph{not} truncated.
#' @param score_metric Metric optimized during PWM fitting. One of \code{"r2"} or \code{"ks"}. \code{"ks"} requires a single binary response.
#' @param bidirect Whether the motif is bi-directional. If TRUE, the reverse-complement is also scored.
#' @param spat_bin_size Size of each spatial bin (bp).
#' @param spat_num_bins Number of spatial bins. Sequence length must be at least \code{spat_bin_size * spat_num_bins}; positions outside this window are ignored. If \code{bidirect = TRUE}, this should be odd (prego symmetrizes the spatial model around the center bin).
#' @param spat_model A previously computed spatial model (the \code{spat} slot of a prior result) to reuse.
#' @param improve_epsilon Minimum improvement in the objective for the optimizer to continue.
#' @param min_nuc_prob Floor on per-position nucleotide probabilities at every iteration.
#' @param unif_prior Uniform prior added to nucleotide probabilities.
#' @param include_response If TRUE (default), the response matrix is stored in the result.
#' @param verbose Show verbose messages from the optimizer.
#' @param seed Random seed.
#' @param consensus_single_thresh,consensus_double_thresh Probability thresholds for calling a single-nucleotide or two-nucleotide IUPAC consensus, respectively.
#' @param match_with_db If TRUE, match the resulting PSSM to the closest motif in \code{motif_dataset} using \code{pssm_match}. The closest match is always returned, even if similarity is low.
#' @param screen_db If TRUE, screen \code{motif_dataset} via \code{\link{screen_pwm}} and add the best database motif to the result (\code{db_motif}, \code{db_motif_pred}, \code{db_motif_pssm}, \code{db_motif_score}).
#' @param motif_dataset A data frame with PSSMs (columns \code{A}, \code{C}, \code{G}, \code{T}, \code{motif}), e.g. \code{HOMER_motifs}, \code{JASPAR_motifs}, or \code{all_motif_datasets()} (default).
#' @param multi_kmers If TRUE (default) and \code{motif = NULL}, generate multiple kmer candidates and pick the best by \code{final_metric}. If \code{motif} is provided, this is ignored. See also \code{return_all}.
#' @param return_all If TRUE, return \emph{all} candidate-kmer regressions instead of only the best one. Requires \code{multi_kmers = TRUE}, \code{motif = NULL}, and \code{motif_num = 1}. Use this when you want N independent kmer-seeded motifs without the residual-rounds approach of \code{motif_num > 1}. Default: FALSE. See \emph{Value} for the returned structure.
#' @param final_metric Metric used to pick the best motif across candidates (and to score the final fit). One of \code{"ks"} or \code{"r2"}. Distinct from \code{score_metric}, which is used \emph{inside} the optimizer. If NULL: \code{"ks"} for binary response, \code{"r2"} otherwise.
#' @param kmer_length Vector of kmer lengths to try in the seed screen.
#' @param max_cands Maximum number of candidate kmers to regress.
#' @param parallel Whether to parallelize. Use \code{set_parallel} to set the number of cores.
#' @param motif_num Number of motifs to infer. If > 1, dispatches to \code{\link{regress_multiple_motifs}} (residual rounds; see Details).
#' @param smooth_k Window size (in observations) for the running-mean residual computed between rounds when \code{motif_num > 1}.
#' @param min_kmer_cor Minimum kmer-response correlation for a kmer to qualify as a seed candidate.
#' @param internal_num_folds Number of internal cross-validation folds during optimization.
#' @param alternative Alternative hypothesis for \code{ks.test}. One of \code{"two.sided"}, \code{"less"}, \code{"greater"}.
#' @param sample_for_kmers If TRUE, run the kmer screen on a random sample of sequences (final regression is still on the full data). Useful for large datasets. Only relevant when \code{multi_kmers = TRUE}.
#' @param sample_frac Fraction of sequences sampled for the kmer screen. Default: 0.1.
#' @param sample_idxs Explicit sequence indices to use for the kmer screen. If NULL, a random sample is drawn.
#' @param sample_ratio For binary response, ratio of '1' to '0' in the sampled subset. Relevant only when \code{sample_frac} is NULL.
#' @param val_frac Fraction of sequences held out for internal validation in the multi-kmer mode. Default: 0.1.
#' @param log_energy If TRUE, the energy is log-transformed at every iteration.
#' @param energy_func Optional function applied to the energy at every iteration; takes and returns a numeric vector (e.g. \code{log} or \code{function(x) x^2}). Input energies are in the range \code{[0, 1]}; if your function was fit on log energies, use \code{log_energy = TRUE}.
#' @param xmin,xmax,npts Range and resolution for interpolating \code{energy_func}.
#' @param energy_func_generator A function that, given the previous-iteration result and the original response, returns an \code{energy_func}. Used in \code{motif_num > 1}: each round, the generator builds an energy function (e.g. a GAM-based one for non-monotonic relationships) and a second pass is run with it. Example:
#' \code{
#' function(prev_reg, resp) {
#'     df <- data.frame(x = prev_reg$pred, y = resp)
#'     model <- mgcv::gam(y ~ s(x, k = 3, bs = "cr"), family = binomial("logit"),
#'                        data = df, method = "REML")
#'     function(z) mgcv::predict.gam(model, newdata = data.frame(x = z))
#' }}
#' @param optimize_pwm If FALSE, the PWM is held fixed and only the spatial model is optimized.
#' @param optimize_spat If FALSE, the spatial model is held fixed and only the PWM is optimized.
#' @param kmer_sequence_length Length of the central window used for the kmer screen. If NULL, the full sequence is used.
#' @param symmetrize_spat If TRUE (default), the spatial model is symmetrized around the center bin.
#'
#' @return The returned structure depends on the mode:
#'
#' \strong{Single-motif mode} (default, or with \code{motif} provided) - a list with:
#' \describe{
#' \item{pssm}{Data frame of the inferred PSSM: rows are positions, columns are nucleotides.}
#' \item{spat}{Data frame of the inferred spatial model (one row per bin).}
#' \item{pred}{Numeric vector of predictions, one per input sequence.}
#' \item{consensus}{IUPAC consensus derived from \code{pssm}.}
#' \item{response}{The response matrix (omitted when \code{include_response = FALSE}).}
#' \item{r2}{Per-response-column \eqn{r^2} of \code{pred} vs the response.}
#' \item{ks}{Kolmogorov-Smirnov test of \code{pred} for response=1 vs response=0 (binary response only).}
#' \item{score}{The KS statistic (binary) or \eqn{r^2} (continuous).}
#' \item{seed_motif}{The kmer/string used as the seed.}
#' \item{kmers}{The screened candidate kmers (only when the seed was found automatically).}
#' \item{predict}{A closure: \code{predict(new_sequences)} returns predictions.}
#' }
#'
#' When \code{match_with_db = TRUE}, also: \code{motif_db}, \code{db_match_cor}, \code{db_match_pssm}, \code{db_match_pred}, \code{db_match_r2}, and (binary) \code{db_match_ks}.
#'
#' When \code{screen_db = TRUE}, also: \code{db_motif}, \code{db_motif_pred}, \code{db_motif_pssm}, \code{db_motif_score}.
#'
#' \strong{Multi-kmer mode with \code{return_all = TRUE}} - a \emph{named list} of single-motif results (named by \code{seed_motif}), one per candidate kmer, sorted by validation score (descending). Each element has the structure above, plus a \code{val_score} field. Refitting behavior:
#' \itemize{
#' \item \code{sample_for_kmers = FALSE} (default): each element's PSSM was fit on the train portion (\code{1 - val_frac} of the full data); \code{pred} therefore covers the train subset only. Call \code{res[[i]]$predict(sequences)} to score the full data, or refit explicitly via \code{regress_pwm(sequences, response, motif = res[[i]]$seed_motif, multi_kmers = FALSE)}.
#' \item \code{sample_for_kmers = TRUE}: each element is refit on the full data (analogous to the single-best path).
#' }
#'
#' \strong{Multi-motif mode (\code{motif_num > 1})} - a list with:
#' \describe{
#' \item{models}{List of single-motif results, one per round.}
#' \item{multi_stats}{Data frame with columns \code{model}, \code{score} (per-motif KS or \eqn{r^2}), \code{comb_score} (linear-combination score using models 1:i), \code{diff}, \code{consensus}, \code{seed_motif}, plus db-match columns when \code{match_with_db = TRUE}.}
#' \item{pred}{Predictions from the combined linear model.}
#' \item{model}{The fitted combined \code{lm} object.}
#' \item{predict}{Closure for predictions from the combined model.}
#' \item{predict_multi}{Closure returning a data frame of per-motif predictions (columns \code{e1}, \code{e2}, ...).}
#' }
#'
#' @examples
#' \dontrun{
#' res <- regress_pwm(sequences_example, response_mat_example)
#' res$pssm
#' res$spat
#' head(res$pred)
#'
#' plot_regression_qc(res)
#'
#' # intialize with a pre-computed PSSM
#' res1 <- regress_pwm(sequences_example, response_mat_example, motif = res$pssm)
#'
#' # intialize with a pre-computed PSSM and spatial model
#' res2 <- regress_pwm(
#'     sequences_example,
#'     response_mat_example,
#'     motif = res$pssm,
#'     spat_model = res$spat
#' )
#'
#' # binary response
#' res_binary <- regress_pwm(cluster_sequences_example, cluster_mat_example[, 1])
#' plot_regression_qc(res_binary)
#'
#' # match with db
#' res_binary <- regress_pwm(cluster_sequences_example, cluster_mat_example[, 1], match_with_db = TRUE)
#' plot_regression_qc(res_binary)
#'
#' # Screen for best db motif
#' res_binary <- regress_pwm(cluster_sequences_example, cluster_mat_example[, 1], screen_db = TRUE)
#' plot_regression_qc(res_binary)
#'
#' # initialize with a motif from the database
#' res_binary <- regress_pwm(
#'     cluster_sequences_example,
#'     cluster_mat_example[, 1],
#'     init_from_dataset = TRUE
#' )
#'
#' # use multiple kmer seeds (returns the single best motif)
#' res_multi <- regress_pwm(
#'     cluster_sequences_example,
#'     cluster_mat_example[, 1],
#'     multi_kmers = TRUE,
#'     kmer_length = 6:8,
#'     final_metric = "ks"
#' )
#' plot_regression_qc(res_multi)
#'
#' # return all candidate-kmer motifs (sorted by validation score)
#' res_all <- regress_pwm(
#'     cluster_sequences_example,
#'     cluster_mat_example[, 1],
#'     multi_kmers = TRUE,
#'     return_all = TRUE,
#'     max_cands = 5
#' )
#' length(res_all)
#' sapply(res_all, function(x) x$seed_motif)
#' sapply(res_all, function(x) x$val_score)
#'
#' # Screen for multiple motifs via residual rounds
#' res_multi <- regress_pwm(
#'     cluster_sequences_example,
#'     cluster_mat_example[, 1],
#'     motif_num = 3,
#'     match_with_db = TRUE
#' )
#' res_multi$multi_stats
#' plot_regression_qc_multi(res_multi)
#' }
#'
#' # regress_multiple_motifs() can also be called directly (equivalent to
#' # regress_pwm() with motif_num > 1, which internally dispatches to it)
#' \dontrun{
#' res_multi2 <- regress_multiple_motifs(
#'     cluster_sequences_example,
#'     cluster_mat_example[, 1],
#'     motif_num = 5,
#'     match_with_db = TRUE
#' )
#' }
#'
#' @inheritParams screen_kmers
#' @inheritDotParams screen_kmers
#' @export
regress_pwm <- function(sequences,
                        response,
                        motif = NULL,
                        motif_length = 15,
                        init_from_dataset = FALSE,
                        score_metric = "r2",
                        bidirect = TRUE,
                        spat_bin_size = NULL,
                        spat_num_bins = NULL,
                        spat_model = NULL,
                        improve_epsilon = 0.0001,
                        min_nuc_prob = 0.001,
                        unif_prior = 0.05,
                        include_response = TRUE,
                        seed = 60427,
                        verbose = FALSE,
                        kmer_length = 8,
                        multi_kmers = TRUE,
                        final_metric = NULL,
                        max_cands = 10,
                        min_gap = 0,
                        max_gap = 1,
                        min_kmer_cor = 0.08,
                        motif_num = 1,
                        smooth_k = 100,
                        consensus_single_thresh = 0.6,
                        consensus_double_thresh = 0.85,
                        internal_num_folds = 1,
                        match_with_db = TRUE,
                        screen_db = FALSE,
                        motif_dataset = all_motif_datasets(),
                        parallel = getOption("prego.parallel", FALSE),
                        alternative = "less",
                        sample_for_kmers = FALSE,
                        sample_frac = NULL,
                        sample_idxs = NULL,
                        sample_ratio = 1,
                        val_frac = 0.1,
                        log_energy = FALSE,
                        energy_func = NULL,
                        xmin = -100,
                        xmax = 100,
                        npts = 1e4,
                        energy_func_generator = NULL,
                        optimize_pwm = TRUE,
                        optimize_spat = TRUE,
                        kmer_sequence_length = NULL,
                        symmetrize_spat = TRUE,
                        return_all = FALSE,
                        ...) {
    if (!is.null(seed)) {
        set.seed(seed)
    }

    if (return_all) {
        if (motif_num > 1) {
            cli_abort("{.field return_all} is incompatible with {.field motif_num} > 1. Use {.field motif_num} = 1 with {.field multi_kmers} = {.val TRUE} to get multiple kmer-seeded motifs.")
        }
        if (!is.null(motif)) {
            cli_abort("{.field return_all} requires {.field motif} = NULL (kmer candidates are generated automatically).")
        }
        if (!multi_kmers) {
            cli_abort("{.field return_all} requires {.field multi_kmers} = {.val TRUE}.")
        }
    }

    if (motif_num > 1) {
        return(
            regress_multiple_motifs(
                sequences = sequences,
                response = response,
                motif = motif,
                motif_length = motif_length,
                score_metric = score_metric,
                bidirect = bidirect,
                spat_bin_size = spat_bin_size,
                spat_num_bins = spat_num_bins,
                spat_model = spat_model,
                improve_epsilon = improve_epsilon,
                min_nuc_prob = min_nuc_prob,
                unif_prior = unif_prior,
                include_response = include_response,
                seed = seed,
                verbose = verbose,
                kmer_length = kmer_length,
                multi_kmers = multi_kmers,
                final_metric = final_metric,
                max_cands = max_cands,
                min_gap = min_gap,
                max_gap = max_gap,
                min_kmer_cor = min_kmer_cor,
                motif_num = motif_num,
                smooth_k = smooth_k,
                consensus_single_thresh = consensus_single_thresh,
                consensus_double_thresh = consensus_double_thresh,
                internal_num_folds = internal_num_folds,
                match_with_db = match_with_db,
                motif_dataset = motif_dataset,
                parallel = parallel,
                alternative = alternative,
                sample_for_kmers = sample_for_kmers,
                sample_frac = sample_frac,
                sample_idxs = sample_idxs,
                sample_ratio = sample_ratio,
                log_energy = log_energy,
                energy_func = energy_func,
                energy_func_generator = energy_func_generator,
                xmin = xmin,
                xmax = xmax,
                npts = npts,
                optimize_pwm = optimize_pwm,
                optimize_spat = optimize_spat,
                kmer_sequence_length = kmer_sequence_length,
                symmetrize_spat = symmetrize_spat,
                ...
            )
        )
    }

    if (!(score_metric %in% c("r2", "ks"))) {
        cli_abort("score_metric must be one of {.val r2} or {.val ks}")
    }

    if (is.null(nrow(response))) {
        response <- matrix(response, ncol = 1)
    }

    if (!all(is.numeric(response))) {
        cli_abort("{.field response} must be numeric")
    }

    if (length(sequences) != nrow(response)) {
        cli_abort("The number of sequences and the number of rows in {.field response} do not match")
    }

    if (any(is.na(sequences))) {
        cli_abort("There are missing values in the sequences")
    }

    max_seq_len <- nchar(sequences[1])
    bins <- calculate_bins(max_seq_len, spat_num_bins, spat_bin_size)
    spat_num_bins <- bins$spat_num_bins
    spat_bin_size <- bins$spat_bin_size
    cli_alert_info("Using {.val {spat_num_bins}} bins of size {.val {spat_bin_size}} bp")

    if (!is.null(spat_model)) {
        # if (!is.data.frame(motif)) {
        #     cli_abort("If {.field spat_model} is provided, {.field motif} must be a previously computed PSSM")
        # }
        validate_spat(spat_model)
        spat_bin <- unique(diff(spat_model$bin))
        spat_model <- spat_model$spat_factor
    }

    if (score_metric == "ks") {
        if (!is_binary_response(response)) {
            cli_abort("When {.field score_metric} is {.val ks}, {.field response} should be a single vector of 0 and 1")
        }
    }

    if (is.null(final_metric)) {
        if (is_binary_response(response)) {
            final_metric <- "ks"
        } else {
            final_metric <- "r2"
        }
    }
    cli_alert_info("Using {.val {final_metric}} as the final metric")

    cli_alert_info("Number of response variables: {.val {ncol(response)}}")

    if (!is.null(energy_func) && !log_energy) {
        cli_warn("Energy function was provided, but {.field log_energy} is {.val FALSE}. Note that the energies during the regression are not log-transformed.")
    }

    spat <- calc_spat_min_max(spat_num_bins, max_seq_len, spat_bin_size)

    if (init_from_dataset) {
        cli_alert_info("Initializing from dataset")
        motif_name <- screen_pwm(sequences, response, metric = final_metric, prior = unif_prior, bidirect = bidirect, only_best = TRUE, alternative = alternative)
        motif <- get_motif_pssm(motif_name$motif)
        motif <- pssm_add_prior(motif, prior = unif_prior)
        cli_alert_info("Best motif from dataset: {.val {motif_name$motif}}")
    }

    if (!is.null(motif) && multi_kmers) {
        cli_warn("Motif is provided, {.field multi_kmers} will be ignored")
    }

    # get motif for initialization (either kmers or pssm)
    kmers <- NULL
    if (is.data.frame(motif)) { # initiazlie with pre-computed PSSM
        pssm <- motif
        if (!all(c("pos", "A", "C", "G", "T") %in% colnames(pssm))) {
            cli_abort("The {.field motif} PSSM data frame should have columns {.val pos}, {.val A}, {.val C}, {.val G}, {.val T}")
        }

        pssm <- pssm_to_mat(pssm)
        consensus <- consensus_from_pssm(pssm, consensus_single_thresh, consensus_double_thresh)

        motif <- ""
        if (!is.na(consensus)) {
            cli_alert_info("Initializing regression with pre-computed PSSM, consensus: {.val {consensus_from_pssm(pssm)}}")
        } else {
            cli_alert_info("Initializing regression with pre-computed PSSM")
        }
    } else { # initialize with kmer
        pssm <- matrix()
        if (is.null(motif)) {
            if (multi_kmers) {
                return(regress_pwm.multi_kmers(
                    sequences = sequences,
                    response = response,
                    motif_length = motif_length,
                    score_metric = score_metric,
                    bidirect = bidirect,
                    spat_bin_size = spat_bin_size,
                    spat_num_bins = spat_num_bins,
                    spat_model = spat_model,
                    improve_epsilon = improve_epsilon,
                    min_nuc_prob = min_nuc_prob,
                    unif_prior = unif_prior,
                    include_response = include_response,
                    seed = seed,
                    verbose = verbose,
                    kmer_length = kmer_length,
                    max_cands = max_cands,
                    min_gap = min_gap,
                    max_gap = max_gap,
                    min_kmer_cor = min_kmer_cor,
                    consensus_single_thresh = consensus_single_thresh,
                    consensus_double_thresh = consensus_double_thresh,
                    internal_num_folds = internal_num_folds,
                    final_metric = final_metric,
                    parallel = parallel,
                    match_with_db = match_with_db,
                    screen_db = screen_db,
                    motif_dataset = motif_dataset,
                    alternative = alternative,
                    val_frac = val_frac,
                    sample_for_kmers = sample_for_kmers,
                    sample_frac = sample_frac,
                    sample_idxs = sample_idxs,
                    sample_ratio = sample_ratio,
                    log_energy = log_energy,
                    energy_func = energy_func,
                    xmin = xmin,
                    xmax = xmax,
                    npts = npts,
                    optimize_pwm = optimize_pwm,
                    optimize_spat = optimize_spat,
                    kmer_sequence_length = kmer_sequence_length,
                    symmetrize_spat = symmetrize_spat,
                    return_all = return_all,
                    ...
                ))
            }
            cli_alert_info("Screening for kmers in order to initialize regression")
            if (sample_for_kmers) {
                cli_alert_info("Subsampling sequences for the kmer screen ({.code sample_for_kmers = TRUE}) to speed up seed selection on large datasets")
                if (is.null(sample_idxs)) {
                    sample_idxs <- sample_response(response, sample_frac, sample_ratio, seed)
                }

                sequences_s <- sequences[sample_idxs]
                response_s <- response[sample_idxs, , drop = FALSE]
            } else {
                sequences_s <- sequences
                response_s <- response
            }
            if (!is.null(kmer_sequence_length)) {
                if (kmer_sequence_length > nchar(sequences[1])) {
                    cli_abort("kmer_sequence_length cannot be greater than the length of the sequences")
                }
                # str_sub the sequence from the middle
                sequences_s <- stringr::str_sub(sequences_s, start = (nchar(sequences_s) - kmer_sequence_length) / 2 + 1, end = (nchar(sequences_s) + kmer_sequence_length) / 2)
            }
            kmers <- screen_kmers(sequences_s, response_s, kmer_length = kmer_length, min_gap = min_gap, max_gap = max_gap, min_cor = min_kmer_cor, ...)
            motif <- kmers$kmer[which.max(abs(kmers$max_r2))]
            if (length(motif) == 0) { # could not find any kmer
                cli_alert_info("Could not find any kmer with correlation above {.val {min_kmer_cor}}. Trying with a threshold of {.val {min_kmer_cor / 2}}")
                kmers <- screen_kmers(sequences_s, response_s, kmer_length = kmer_length, min_gap = min_gap, max_gap = max_gap, min_cor = min_kmer_cor / 2, ...)
                motif <- kmers$kmer[which.max(abs(kmers$max_r2))]
                if (length(motif) == 0) {
                    motif <- paste(rep("*", motif_length), collapse = "")
                    cli_alert_info("Could not find any kmer. Initializing with {.val {motif}}")
                }
            }
        }
        if (!is.character(motif)) {
            cli_abort("The motif must be a either a character string or a data frame with the PSSM")
        }
        if (stringr::str_length(motif) < motif_length) {
            motif <- stringr::str_pad(motif, motif_length, "*", side = "both")
            cli_alert_info("Motif is shorter than {.val {motif_length}}, extending with wildcards")

            # substitute 'N' with wildcards
            motif <- stringr::str_replace_all(motif, "N", "*")
        }

        cli_alert_info("Initializing regression with the following motif: {.val {motif}}")
    }


    cli_alert_info("Running regression")
    cli_ul(c(
        "Motif length: {.val {motif_length}}",
        "Bidirectional: {.val {bidirect}}",
        "Spat min: {.val {spat$spat_min}}",
        "Spat max: {.val {spat$spat_max}}",
        "Spat bin size: {.val {spat_bin_size}}",
        "Number of bins: {.val {spat_num_bins}}",
        "Improve epsilon: {.val {improve_epsilon}}",
        "Min nuc prob: {.val {min_nuc_prob}}",
        "Uniform prior: {.val {unif_prior}}",
        "Score metric: {.val {score_metric}}",
        "Seed: {.val {seed}}"
    ))

    sequences_full <- sequences
    sequences <- stringr::str_sub(sequences, start = spat$spat_min + 1, end = spat$spat_max)

    is_train <- rep(TRUE, length(sequences))

    res <- regress_pwm_cpp(
        toupper(sequences),
        response,
        is_train,
        motif = motif,
        spat_bin = spat_bin_size,
        spat_min = 0,
        spat_max = nchar(sequences[1]),
        min_nuc_prob = min_nuc_prob,
        spat_factor = spat_model,
        improve_epsilon = improve_epsilon,
        is_bidirect = bidirect,
        unif_prior = unif_prior,
        score_metric = score_metric,
        verbose = verbose,
        seed = seed %||% 60427,
        pssm_mat = pssm,
        consensus_single_thresh = consensus_single_thresh,
        consensus_double_thresh = consensus_double_thresh,
        num_folds = internal_num_folds,
        log_energy = log_energy,
        energy_func = energy_func,
        xmin = xmin,
        xmax = xmax,
        npts = npts,
        optimize_pwm = optimize_pwm,
        optimize_spat = optimize_spat,
        symmetrize_spat = symmetrize_spat
    )


    if (include_response) {
        res$response <- response
    }

    res$r2 <- tgs_cor(response, as.matrix(res$pred))[, 1]^2
    res$seed_motif <- motif

    if (is_binary_response(response)) {
        res$ks <- suppressWarnings(ks.test(res$pred[as.logical(response[, 1])], res$pred[!as.logical(response[, 1])], alternative = alternative))
        res$score <- res$ks$statistic
    } else {
        res$score <- res$r2
    }

    if (!is.null(kmers)) {
        res$kmers <- kmers
    }

    res$consensus <- consensus_from_pssm(res$pssm, consensus_single_thresh, consensus_double_thresh)
    cli_alert_success("Finished running regression. Consensus: {.val {res$consensus}}")


    if (match_with_db) {
        res <- add_regression_db_match(res, sequences, motif_dataset, alternative = alternative)
    }

    if (screen_db) {
        res <- add_regression_db_screen(res, response, sequences, motif_dataset, final_metric, prior = unif_prior, bidirect = bidirect, alternative = alternative, parallel = parallel)
    }

    res$spat_min <- spat$spat_min
    res$spat_max <- spat$spat_max
    res$spat_bin_size <- spat_bin_size
    res$bidirect <- bidirect
    res$seq_length <- nchar(sequences[1])

    res <- add_predict_function(res, spat, bidirect, energy_func)
    res$pred <- res$predict(sequences_full)

    res$r2 <- tgs_cor(response, as.matrix(res$pred))[, 1]^2
    if (is_binary_response(response)) {
        res$ks <- suppressWarnings(ks.test(res$pred[as.logical(response[, 1])], res$pred[!as.logical(response[, 1])], alternative = alternative))
        res$score <- res$ks$statistic
    } else {
        res$score <- res$r2
    }

    if (is_binary_response(response)) {
        cli_alert_success("KS test D: {.val {round(res$ks$statistic, digits=4)}}, p-value: {.val {res$ks$p.value}}")
    } else {
        cli_alert_success("R^2: {.val {round(res$r2, digits=4)}}")
    }

    return(res)
}

add_predict_function <- function(res, spat, bidirect, energy_func) {
    func_env <- new.env()
    func_env$pssm <- res$pssm
    func_env$spat <- res$spat
    func_env$energy_func <- energy_func
    func_env$bidirect <- bidirect
    func_env$spat_min <- spat$spat_min
    func_env$spat_max <- spat$spat_max

    res$predict <- function(x) {
        x <- stringr::str_sub(x, start = spat_min + 1, end = spat_max)
        e <- compute_pwm(x, pssm, spat = spat, bidirect = bidirect, prior = 0)
        if (!is.null(energy_func)) {
            e <- energy_func(e)
        }
        return(e)
    }

    environment(res$predict) <- func_env

    return(res)
}

add_regression_db_screen <- function(res, response, sequences, motif_dataset, metric, prior, bidirect, alternative, parallel = getOption("prego.parallel", TRUE)) {
    scr <- screen_pwm(sequences, response, motif_dataset, metric = metric, prior = prior, bidirect = bidirect, parallel = parallel, alternative = alternative, only_best = TRUE)

    cli_alert_info("Best db motif: {.val {scr$motif[1]}}")
    cli_alert_info("Best db motif score ({.val {metric}}): {.val {scr$score[1]}}")
    res$db_motif <- scr$motif[1]
    res$db_motif_pred <- extract_pwm(sequences, scr$motif[1], prior = prior, bidirect = bidirect)[, 1]
    res$db_motif_pssm <- get_motif_pssm(scr$motif[1])
    res$db_motif_score <- scr$score[1]

    return(res)
}

add_regression_db_match <- function(reg, sequences, motif_dataset, alternative, parallel = getOption("prego.parallel", TRUE)) {
    best_match <- pssm_match(reg$pssm, motif_dataset)[1, ]
    reg$db_match <- best_match$motif
    reg$db_match_cor <- best_match$cor
    cli_alert_info("Best match in the database: {.val {best_match$motif}}, cor: {.val {round(best_match$cor, digits = 3)}}")
    reg$db_match_pssm <- motif_dataset %>%
        filter(motif == best_match$motif) %>%
        select(pos, A, C, G, T)
    reg$db_match_pred <- compute_pwm(sequences, reg$db_match_pssm)
    reg$db_match_r2 <- tgs_cor(as.matrix(reg$response), as.matrix(reg$db_match_pred))[, 1]^2
    if (is_binary_response(reg$response)) {
        reg$db_match_ks <- suppressWarnings(ks.test(reg$db_match_pred[as.logical(reg$response[, 1])], reg$db_match_pred[!as.logical(reg$response[, 1])], alternative = alternative))
        cli_alert_success("{.val {reg$db_match}} KS test D: {.val {round(reg$db_match_ks$statistic, digits=4)}}, p-value: {.val {reg$db_match_ks$p.value}}")
    }
    return(reg)
}
